
#pragma once

#include <cstdint>


namespace Core
{
	class Cpu;

	class Instructions
	{
	public:
		static uint8_t Instr_INVALID(Cpu* cpu);

		// Misc / Control Instructions
		static uint8_t Instr_0x00_MISC_NOP(Cpu* cpu);
		static uint8_t Instr_0x10_MISC_STOP(Cpu* cpu);
		static uint8_t Instr_0x76_MISC_HALT(Cpu* cpu);
		static uint8_t Instr_0xCB_MISC_PREFIX(Cpu* cpu);
		static uint8_t Instr_0xF3_MISC_DI(Cpu* cpu);
		static uint8_t Instr_0xFB_MISC_IE(Cpu* cpu);

		// Jumps/Calls
		static uint8_t Instr_0x18_JPCALL_JR_e8(Cpu* cpu);
		static uint8_t Instr_0x20_JPCALL_JR_NZ_e8(Cpu* cpu);
		static uint8_t Instr_0x28_JPCALL_JR_Z_e8(Cpu* cpu);
		static uint8_t Instr_0x30_JPCALL_JR_NC_e8(Cpu* cpu);
		static uint8_t Instr_0x38_JPCALL_JR_C_e8(Cpu* cpu);
		static uint8_t Instr_0xC0_JPCALL_RET_NZ(Cpu* cpu);
		static uint8_t Instr_0xC2_JPCALL_JP_NZ_a16(Cpu* cpu);
		static uint8_t Instr_0xC3_JPCALL_JP_a16(Cpu* cpu);
		static uint8_t Instr_0xC4_JPCALL_CALL_NZ_a16(Cpu* cpu);
		static uint8_t Instr_0xC7_JPCALL_RST_00(Cpu* cpu);
		static uint8_t Instr_0xC8_JPCALL_RET_Z(Cpu* cpu);
		static uint8_t Instr_0xC9_JPCALL_RET(Cpu* cpu);
		static uint8_t Instr_0xCA_JPCALL_JP_Z_a16(Cpu* cpu);
		static uint8_t Instr_0xCC_JPCALL_CALL_Z_a16(Cpu* cpu);
		static uint8_t Instr_0xCD_JPCALL_CALL_a16(Cpu* cpu);
		static uint8_t Instr_0xCF_JPCALL_RST_08(Cpu* cpu);
		static uint8_t Instr_0xD0_JPCALL_RET_NC(Cpu* cpu);
		static uint8_t Instr_0xD2_JPCALL_JP_NC_a16(Cpu* cpu);
		static uint8_t Instr_0xD4_JPCALL_VALL_NC_a16(Cpu* cpu);
		static uint8_t Instr_0xD7_JPCALL_RST_10(Cpu* cpu);
		static uint8_t Instr_0xD8_JPCALL_RET_C(Cpu* cpu);
		static uint8_t Instr_0xD9_JPCALL_RETI(Cpu* cpu);
		static uint8_t Instr_0xDA_JPCALL_JP_C_a16(Cpu* cpu);
		static uint8_t Instr_0xDC_JPCALL_CALL_C_a16(Cpu* cpu);
		static uint8_t Instr_0xDF_JPCALL_RST_18(Cpu* cpu);
		static uint8_t Instr_0xE7_JPCALL_RST_20(Cpu* cpu);
		static uint8_t Instr_0xE9_JPCALL_JP_HL(Cpu* cpu);
		static uint8_t Instr_0xEF_JPCALL_RST_28(Cpu* cpu);
		static uint8_t Instr_0xF7_JPCALL_RST_30(Cpu* cpu);
		static uint8_t Instr_0xFF_JPCALL_RST_38(Cpu* cpu);

		// 8-bit Load Instructions
		static uint8_t Instr_0x02_8LD_BC_A(Cpu * cpu);
		static uint8_t Instr_0x12_8LD_DE_A(Cpu * cpu);
		static uint8_t Instr_0x0A_8LD_A_BC(Cpu * cpu);
		static uint8_t Instr_0x1A_8LD_A_DE(Cpu * cpu);
		static uint8_t Instr_0x46_8LD_B_HL(Cpu * cpu);
		static uint8_t Instr_0x4E_8LD_C_HL(Cpu * cpu);
		static uint8_t Instr_0x56_8LD_D_HL(Cpu * cpu);
		static uint8_t Instr_0x5E_8LD_E_HL(Cpu * cpu);
		static uint8_t Instr_0x66_8LD_H_HL(Cpu * cpu);
		static uint8_t Instr_0x6E_8LD_L_HL(Cpu * cpu);
		static uint8_t Instr_0x7E_8LD_A_HL(Cpu * cpu);
		static uint8_t Instr_0x06_8LD_B_e8(Cpu * cpu);
		static uint8_t Instr_0x0E_8LD_C_e8(Cpu * cpu);
		static uint8_t Instr_0x16_8LD_D_e8(Cpu * cpu);
		static uint8_t Instr_0x1E_8LD_E_e8(Cpu * cpu);
		static uint8_t Instr_0x26_8LD_H_e8(Cpu * cpu);
		static uint8_t Instr_0x2E_8LD_L_e8(Cpu * cpu);
		static uint8_t Instr_0x3A_8LD_A_HLDEC(Cpu* cpu);
		static uint8_t Instr_0x22_8LD_HLINC_A(Cpu* cpu);
		static uint8_t Instr_0x2A_8LD_A_HLINC(Cpu* cpu);
		static uint8_t Instr_0x32_8LD_HLDEC_A(Cpu* cpu);
		static uint8_t Instr_0x36_8LD_HL_e8(Cpu* cpu);
		static uint8_t Instr_0x3E_8LD_A_e8(Cpu* cpu);
		static uint8_t Instr_0x40_8LD_B_B(Cpu * cpu);
		static uint8_t Instr_0x41_8LD_B_C(Cpu * cpu);
		static uint8_t Instr_0x42_8LD_B_D(Cpu * cpu);
		static uint8_t Instr_0x43_8LD_B_E(Cpu * cpu);
		static uint8_t Instr_0x44_8LD_B_H(Cpu * cpu);
		static uint8_t Instr_0x45_8LD_B_L(Cpu * cpu);
		static uint8_t Instr_0x47_8LD_B_A(Cpu * cpu);
		static uint8_t Instr_0x48_8LD_C_B(Cpu * cpu);
		static uint8_t Instr_0x49_8LD_C_C(Cpu * cpu);
		static uint8_t Instr_0x4A_8LD_C_D(Cpu * cpu);
		static uint8_t Instr_0x4B_8LD_C_E(Cpu * cpu);
		static uint8_t Instr_0x4C_8LD_C_H(Cpu * cpu);
		static uint8_t Instr_0x4D_8LD_C_L(Cpu * cpu);
		static uint8_t Instr_0x4F_8LD_C_A(Cpu * cpu);
		static uint8_t Instr_0x50_8LD_D_B(Cpu * cpu);
		static uint8_t Instr_0x51_8LD_D_C(Cpu * cpu);
		static uint8_t Instr_0x52_8LD_D_D(Cpu * cpu);
		static uint8_t Instr_0x53_8LD_D_E(Cpu * cpu);
		static uint8_t Instr_0x54_8LD_D_H(Cpu * cpu);
		static uint8_t Instr_0x55_8LD_D_L(Cpu * cpu);
		static uint8_t Instr_0x57_8LD_D_A(Cpu * cpu);
		static uint8_t Instr_0x58_8LD_E_B(Cpu * cpu);
		static uint8_t Instr_0x59_8LD_E_C(Cpu * cpu);
		static uint8_t Instr_0x5A_8LD_E_D(Cpu * cpu);
		static uint8_t Instr_0x5B_8LD_E_E(Cpu * cpu);
		static uint8_t Instr_0x5C_8LD_E_H(Cpu * cpu);
		static uint8_t Instr_0x5D_8LD_E_L(Cpu * cpu);
		static uint8_t Instr_0x5F_8LD_E_A(Cpu * cpu);
		static uint8_t Instr_0x60_8LD_H_B(Cpu * cpu);
		static uint8_t Instr_0x61_8LD_H_C(Cpu * cpu);
		static uint8_t Instr_0x62_8LD_H_D(Cpu * cpu);
		static uint8_t Instr_0x63_8LD_H_E(Cpu * cpu);
		static uint8_t Instr_0x64_8LD_H_H(Cpu * cpu);
		static uint8_t Instr_0x65_8LD_H_L(Cpu * cpu);
		static uint8_t Instr_0x67_8LD_H_A(Cpu * cpu);
		static uint8_t Instr_0x68_8LD_L_B(Cpu * cpu);
		static uint8_t Instr_0x69_8LD_L_C(Cpu * cpu);
		static uint8_t Instr_0x6A_8LD_L_D(Cpu * cpu);
		static uint8_t Instr_0x6B_8LD_L_E(Cpu * cpu);
		static uint8_t Instr_0x6C_8LD_L_H(Cpu * cpu);
		static uint8_t Instr_0x6D_8LD_L_L(Cpu * cpu);
		static uint8_t Instr_0x6F_8LD_L_A(Cpu * cpu);
		static uint8_t Instr_0x78_8LD_A_B(Cpu * cpu);
		static uint8_t Instr_0x79_8LD_A_C(Cpu * cpu);
		static uint8_t Instr_0x7A_8LD_A_D(Cpu * cpu);
		static uint8_t Instr_0x7B_8LD_A_E(Cpu * cpu);
		static uint8_t Instr_0x7C_8LD_A_H(Cpu * cpu);
		static uint8_t Instr_0x7D_8LD_A_L(Cpu * cpu);
		static uint8_t Instr_0x7F_8LD_A_A(Cpu * cpu);
		static uint8_t Instr_0x70_8LD_HL_B(Cpu * cpu);
		static uint8_t Instr_0x71_8LD_HL_C(Cpu * cpu);
		static uint8_t Instr_0x72_8LD_HL_D(Cpu * cpu);
		static uint8_t Instr_0x73_8LD_HL_E(Cpu * cpu);
		static uint8_t Instr_0x74_8LD_HL_H(Cpu * cpu);
		static uint8_t Instr_0x75_8LD_HL_L(Cpu * cpu);
		static uint8_t Instr_0x77_8LD_HL_A(Cpu * cpu);
		static uint8_t Instr_0xE0_8LD_a8_A(Cpu * cpu);
		static uint8_t Instr_0xE2_8LD_CADDR_A(Cpu * cpu);
		static uint8_t Instr_0xEA_8LD_a16_A(Cpu * cpu);
		static uint8_t Instr_0xF0_8LD_A_a8(Cpu * cpu);
		static uint8_t Instr_0xF2_8LD_A_CADDR(Cpu * cpu);
		static uint8_t Instr_0xFA_8LD_A_a16(Cpu * cpu);

		// 16-bit Load Instructions
		static uint8_t Instr_0x01_16LD_BC_e16(Cpu * cpu);
		static uint8_t Instr_0x11_16LD_DE_e16(Cpu * cpu);
		static uint8_t Instr_0x21_16LD_HL_e16(Cpu * cpu);
		static uint8_t Instr_0x31_16LD_SP_e16(Cpu * cpu);
		static uint8_t Instr_0x08_16LD_a16_SP(Cpu * cpu);
		static uint8_t Instr_0xC1_16LD_POP_BC(Cpu * cpu);
		static uint8_t Instr_0xC5_16LD_PUSH_BC(Cpu * cpu);
		static uint8_t Instr_0xD1_16LD_POP_DE(Cpu * cpu);
		static uint8_t Instr_0xD5_16LD_PUSH_DE(Cpu * cpu);
		static uint8_t Instr_0xE1_16LD_POP_HL(Cpu * cpu);
		static uint8_t Instr_0xE5_16LD_PUSH_DL(Cpu * cpu);
		static uint8_t Instr_0xF1_16LD_POP_AF(Cpu * cpu);
		static uint8_t Instr_0xF5_16LD_PUSH_AF(Cpu * cpu);
		static uint8_t Instr_0xF8_16LD_SP_e8(Cpu * cpu);
		static uint8_t Instr_0xF9_16LD_SP_HL(Cpu * cpu);

		// 8-bit Arithmetic/Logical Instructions
		static uint8_t Instr_0x04_8ALU_INC_B(Cpu * cpu);
		static uint8_t Instr_0x0C_8ALU_INC_C(Cpu * cpu);
		static uint8_t Instr_0x14_8ALU_INC_D(Cpu * cpu);
		static uint8_t Instr_0x1C_8ALU_INC_E(Cpu * cpu);
		static uint8_t Instr_0x24_8ALU_INC_H(Cpu * cpu);
		static uint8_t Instr_0x2C_8ALU_INC_L(Cpu * cpu);
		static uint8_t Instr_0x34_8ALU_INC_HL(Cpu * cpu);
		static uint8_t Instr_0x3C_8ALU_INC_A(Cpu * cpu);
		static uint8_t Instr_0x05_8ALU_DEC_B(Cpu * cpu);
		static uint8_t Instr_0x0D_8ALU_DEC_C(Cpu * cpu);
		static uint8_t Instr_0x15_8ALU_DEC_D(Cpu * cpu);
		static uint8_t Instr_0x1D_8ALU_DEC_E(Cpu * cpu);
		static uint8_t Instr_0x25_8ALU_DEC_H(Cpu * cpu);
		static uint8_t Instr_0x2D_8ALU_DEC_L(Cpu * cpu);
		static uint8_t Instr_0x35_8ALU_DEC_HL(Cpu * cpu);
		static uint8_t Instr_0x3D_8ALU_DEC_A(Cpu * cpu);
		static uint8_t Instr_0x80_8ALU_ADD_B(Cpu * cpu);
		static uint8_t Instr_0x81_8ALU_ADD_C(Cpu * cpu);
		static uint8_t Instr_0x82_8ALU_ADD_D(Cpu * cpu);
		static uint8_t Instr_0x83_8ALU_ADD_E(Cpu * cpu);
		static uint8_t Instr_0x84_8ALU_ADD_H(Cpu * cpu);
		static uint8_t Instr_0x85_8ALU_ADD_L(Cpu * cpu);
		static uint8_t Instr_0x86_8ALU_ADD_HL(Cpu * cpu);
		static uint8_t Instr_0x87_8ALU_ADD_A(Cpu * cpu);
		static uint8_t Instr_0xC6_8ALU_ADD_e8(Cpu * cpu);
		static uint8_t Instr_0x88_8ALU_ADC_B(Cpu * cpu);
		static uint8_t Instr_0x89_8ALU_ADC_C(Cpu * cpu);
		static uint8_t Instr_0x8A_8ALU_ADC_D(Cpu * cpu);
		static uint8_t Instr_0x8B_8ALU_ADC_E(Cpu * cpu);
		static uint8_t Instr_0x8C_8ALU_ADC_H(Cpu * cpu);
		static uint8_t Instr_0x8D_8ALU_ADC_L(Cpu * cpu);
		static uint8_t Instr_0x8E_8ALU_ADC_HL(Cpu * cpu);
		static uint8_t Instr_0x8F_8ALU_ADC_A(Cpu * cpu);
		static uint8_t Instr_0xCE_8ALU_ADC_e8(Cpu * cpu);
		static uint8_t Instr_0x90_8ALU_SUB_B(Cpu * cpu);
		static uint8_t Instr_0x91_8ALU_SUB_C(Cpu * cpu);
		static uint8_t Instr_0x92_8ALU_SUB_D(Cpu * cpu);
		static uint8_t Instr_0x93_8ALU_SUB_E(Cpu * cpu);
		static uint8_t Instr_0x94_8ALU_SUB_H(Cpu * cpu);
		static uint8_t Instr_0x95_8ALU_SUB_L(Cpu * cpu);
		static uint8_t Instr_0x96_8ALU_SUB_HL(Cpu * cpu);
		static uint8_t Instr_0x97_8ALU_SUB_A(Cpu * cpu);
		static uint8_t Instr_0xD6_8ALU_SUB_e8(Cpu * cpu);
		static uint8_t Instr_0x98_8ALU_SBC_B(Cpu * cpu);
		static uint8_t Instr_0x99_8ALU_SBC_D(Cpu * cpu);
		static uint8_t Instr_0x9A_8ALU_SBC_D(Cpu * cpu);
		static uint8_t Instr_0x9B_8ALU_SBC_E(Cpu * cpu);
		static uint8_t Instr_0x9C_8ALU_SBC_H(Cpu * cpu);
		static uint8_t Instr_0x9D_8ALU_SBC_L(Cpu * cpu);
		static uint8_t Instr_0x9E_8ALU_SBC_HL(Cpu * cpu);
		static uint8_t Instr_0x9F_8ALU_SBC_A(Cpu * cpu);
		static uint8_t Instr_0xDE_8ALU_SBC_e8(Cpu * cpu);
		static uint8_t Instr_0xA0_8ALU_AND_B(Cpu * cpu);
		static uint8_t Instr_0xA1_8ALU_AND_C(Cpu * cpu);
		static uint8_t Instr_0xA2_8ALU_AND_D(Cpu * cpu);
		static uint8_t Instr_0xA3_8ALU_AND_E(Cpu * cpu);
		static uint8_t Instr_0xA4_8ALU_AND_H(Cpu * cpu);
		static uint8_t Instr_0xA5_8ALU_AND_L(Cpu * cpu);
		static uint8_t Instr_0xA6_8ALU_AND_HL(Cpu * cpu);
		static uint8_t Instr_0xA7_8ALU_AND_A(Cpu * cpu);
		static uint8_t Instr_0xE6_8ALU_AND_e8(Cpu * cpu);
		static uint8_t Instr_0xA8_8ALU_XOR_B(Cpu * cpu);
		static uint8_t Instr_0xA9_8ALU_XOR_C(Cpu * cpu);
		static uint8_t Instr_0xAA_8ALU_XOR_D(Cpu * cpu);
		static uint8_t Instr_0xAB_8ALU_XOR_E(Cpu * cpu);
		static uint8_t Instr_0xAC_8ALU_XOR_H(Cpu * cpu);
		static uint8_t Instr_0xAD_8ALU_XOR_L(Cpu * cpu);
		static uint8_t Instr_0xAE_8ALU_XOR_HL(Cpu * cpu);
		static uint8_t Instr_0xAF_8ALU_XOR_A(Cpu * cpu);
		static uint8_t Instr_0xEE_8ALU_XOR_e8(Cpu * cpu);
		static uint8_t Instr_0xB0_8ALU_OR_B(Cpu * cpu);
		static uint8_t Instr_0xB1_8ALU_OR_C(Cpu * cpu);
		static uint8_t Instr_0xB2_8ALU_OR_D(Cpu * cpu);
		static uint8_t Instr_0xB3_8ALU_OR_E(Cpu * cpu);
		static uint8_t Instr_0xB4_8ALU_OR_H(Cpu * cpu);
		static uint8_t Instr_0xB5_8ALU_OR_L(Cpu * cpu);
		static uint8_t Instr_0xB6_8ALU_OR_HL(Cpu * cpu);
		static uint8_t Instr_0xB7_8ALU_OR_A(Cpu * cpu);
		static uint8_t Instr_0xF6_8ALU_OR_e8(Cpu * cpu);
		static uint8_t Instr_0xB8_8ALU_CP_B(Cpu * cpu);
		static uint8_t Instr_0xB9_8ALU_CP_C(Cpu * cpu);
		static uint8_t Instr_0xBA_8ALU_CP_D(Cpu * cpu);
		static uint8_t Instr_0xBB_8ALU_CP_E(Cpu * cpu);
		static uint8_t Instr_0xBC_8ALU_CP_H(Cpu * cpu);
		static uint8_t Instr_0xBD_8ALU_CP_L(Cpu * cpu);
		static uint8_t Instr_0xBE_8ALU_CP_HL(Cpu * cpu);
		static uint8_t Instr_0xBF_8ALU_CP_A(Cpu * cpu);
		static uint8_t Instr_0xFE_8ALU_CP_e8(Cpu * cpu);

		// 16-bit Arithmetic/Logical Instructions
		static uint8_t Instr_0x03_16ALU_INC_BC(Cpu * cpu);
		static uint8_t Instr_0x13_16ALU_INC_DE(Cpu * cpu);
		static uint8_t Instr_0x23_16ALU_INC_HL(Cpu * cpu);
		static uint8_t Instr_0x33_16ALU_INC_SP(Cpu * cpu);
		static uint8_t Instr_0x0B_16ALU_DEC_BC(Cpu * cpu);
		static uint8_t Instr_0x1B_16ALU_DEC_DE(Cpu * cpu);
		static uint8_t Instr_0x2B_16ALU_DEC_HL(Cpu * cpu);
		static uint8_t Instr_0x3B_16ALU_DEC_SP(Cpu * cpu);
		static uint8_t Instr_0x09_16ALU_ADD_BC(Cpu * cpu);
		static uint8_t Instr_0x19_16ALU_ADD_DE(Cpu * cpu);
		static uint8_t Instr_0x29_16ALU_ADD_HL(Cpu * cpu);
		static uint8_t Instr_0x39_16ALU_ADD_SP(Cpu * cpu);
		static uint8_t Instr_0xE8_16ALU_ADD_SP_e8(Cpu * cpu);

		// 8-bit Shift, Rotate and Bit Instructions
		static uint8_t Instr_0x07_8SRB_RLCA(Cpu * cpu);
		static uint8_t Instr_0x0F_8SRB_RRCA(Cpu * cpu);
		static uint8_t Instr_0x17_8SRB_RLA(Cpu * cpu);
		static uint8_t Instr_0x1F_8SRB_RRA(Cpu * cpu);
		static uint8_t Instr_0x27_8SRB_DAA(Cpu * cpu);
		static uint8_t Instr_0x2F_8SRB_CPL(Cpu * cpu);
		static uint8_t Instr_0x37_8SRB_SCF(Cpu * cpu);
		static uint8_t Instr_0x3F_8SRB_CCF(Cpu * cpu);

		// 16-bit PREFIX Instructions
		static uint8_t Instr_16_0xCB00_RLC_B(Cpu* cpu);   
		static uint8_t Instr_16_0xCB01_RLC_C(Cpu* cpu);   
		static uint8_t Instr_16_0xCB02_RLC_D(Cpu* cpu);   
		static uint8_t Instr_16_0xCB03_RLC_E(Cpu* cpu);   
		static uint8_t Instr_16_0xCB04_RLC_H(Cpu* cpu);   
		static uint8_t Instr_16_0xCB05_RLC_L(Cpu* cpu);   
		static uint8_t Instr_16_0xCB06_RLC_HL(Cpu* cpu);  
		static uint8_t Instr_16_0xCB07_RLC_A(Cpu* cpu);   
		static uint8_t Instr_16_0xCB08_RRC_B(Cpu* cpu);   
		static uint8_t Instr_16_0xCB09_RRC_C(Cpu* cpu);   
		static uint8_t Instr_16_0xCB0A_RRC_D(Cpu* cpu);   
		static uint8_t Instr_16_0xCB0B_RRC_E(Cpu* cpu);   
		static uint8_t Instr_16_0xCB0C_RRC_H(Cpu* cpu);   
		static uint8_t Instr_16_0xCB0D_RRC_L(Cpu* cpu);   
		static uint8_t Instr_16_0xCB0E_RRC_HL(Cpu* cpu);  
		static uint8_t Instr_16_0xCB0F_RRC_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCB10_RL_B(Cpu* cpu);  
		static uint8_t Instr_16_0xCB11_RL_C(Cpu* cpu);  
		static uint8_t Instr_16_0xCB12_RL_D(Cpu* cpu);  
		static uint8_t Instr_16_0xCB13_RL_E(Cpu* cpu);  
		static uint8_t Instr_16_0xCB14_RL_H(Cpu* cpu);  
		static uint8_t Instr_16_0xCB15_RL_L(Cpu* cpu);  
		static uint8_t Instr_16_0xCB16_RL_HL(Cpu* cpu); 
		static uint8_t Instr_16_0xCB17_RL_A(Cpu* cpu);  
		static uint8_t Instr_16_0xCB18_RR_B(Cpu* cpu);  
		static uint8_t Instr_16_0xCB19_RR_C(Cpu* cpu);  
		static uint8_t Instr_16_0xCB1A_RR_D(Cpu* cpu);  
		static uint8_t Instr_16_0xCB1B_RR_E(Cpu* cpu);  
		static uint8_t Instr_16_0xCB1C_RR_H(Cpu* cpu);  
		static uint8_t Instr_16_0xCB1D_RR_L(Cpu* cpu);  
		static uint8_t Instr_16_0xCB1E_RR_HL(Cpu* cpu); 
		static uint8_t Instr_16_0xCB1F_RR_A(Cpu* cpu);  
		static uint8_t Instr_16_0xCB20_SLA_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCB21_SLA_C(Cpu* cpu);   
		static uint8_t Instr_16_0xCB22_SLA_D(Cpu* cpu);   
		static uint8_t Instr_16_0xCB23_SLA_E(Cpu* cpu);   
		static uint8_t Instr_16_0xCB24_SLA_H(Cpu* cpu);   
		static uint8_t Instr_16_0xCB25_SLA_L(Cpu* cpu);   
		static uint8_t Instr_16_0xCB26_SLA_HL(Cpu* cpu);  
		static uint8_t Instr_16_0xCB27_SLA_A(Cpu* cpu);   
		static uint8_t Instr_16_0xCB28_SRA_B(Cpu* cpu);   
		static uint8_t Instr_16_0xCB29_SRA_C(Cpu* cpu);   
		static uint8_t Instr_16_0xCB2A_SRA_D(Cpu* cpu);   
		static uint8_t Instr_16_0xCB2B_SRA_E(Cpu* cpu);   
		static uint8_t Instr_16_0xCB2C_SRA_H(Cpu* cpu);   
		static uint8_t Instr_16_0xCB2D_SRA_L(Cpu* cpu);   
		static uint8_t Instr_16_0xCB2E_SRA_HL(Cpu* cpu);  
		static uint8_t Instr_16_0xCB2F_SRA_A(Cpu* cpu);   
		static uint8_t Instr_16_0xCB30_SWAP_B(Cpu* cpu);  
		static uint8_t Instr_16_0xCB31_SWAP_C(Cpu* cpu);  
		static uint8_t Instr_16_0xCB32_SWAP_D(Cpu* cpu);  
		static uint8_t Instr_16_0xCB33_SWAP_E(Cpu* cpu);  
		static uint8_t Instr_16_0xCB34_SWAP_H(Cpu* cpu);  
		static uint8_t Instr_16_0xCB35_SWAP_L(Cpu* cpu);  
		static uint8_t Instr_16_0xCB36_SWAP_HL(Cpu* cpu); 
		static uint8_t Instr_16_0xCB37_SWAP_A(Cpu* cpu);  
		static uint8_t Instr_16_0xCB38_SRL_B(Cpu* cpu);   
		static uint8_t Instr_16_0xCB39_SRL_C(Cpu* cpu);   
		static uint8_t Instr_16_0xCB3A_SRL_D(Cpu* cpu);   
		static uint8_t Instr_16_0xCB3B_SRL_E(Cpu* cpu);   
		static uint8_t Instr_16_0xCB3C_SRL_H(Cpu* cpu);   
		static uint8_t Instr_16_0xCB3D_SRL_L(Cpu* cpu);   
		static uint8_t Instr_16_0xCB3E_SRL_HL(Cpu* cpu);  
		static uint8_t Instr_16_0xCB3F_SRL_A(Cpu* cpu);   
		static uint8_t Instr_16_0xCB40_BIT_0_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCB41_BIT_0_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCB42_BIT_0_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCB43_BIT_0_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCB44_BIT_0_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCB45_BIT_0_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCB46_BIT_0_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCB47_BIT_0_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCB48_BIT_1_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCB49_BIT_1_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCB4A_BIT_1_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCB4B_BIT_1_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCB4C_BIT_1_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCB4D_BIT_1_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCB4E_BIT_1_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCB4F_BIT_1_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCB50_BIT_2_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCB51_BIT_2_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCB52_BIT_2_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCB53_BIT_2_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCB54_BIT_2_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCB55_BIT_2_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCB56_BIT_2_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCB57_BIT_2_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCB58_BIT_3_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCB59_BIT_3_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCB5A_BIT_3_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCB5B_BIT_3_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCB5C_BIT_3_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCB5D_BIT_3_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCB5E_BIT_3_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCB5F_BIT_3_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCB60_BIT_4_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCB61_BIT_4_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCB62_BIT_4_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCB63_BIT_4_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCB64_BIT_4_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCB65_BIT_4_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCB66_BIT_4_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCB67_BIT_4_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCB68_BIT_5_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCB69_BIT_5_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCB6A_BIT_5_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCB6B_BIT_5_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCB6C_BIT_5_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCB6D_BIT_5_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCB6E_BIT_5_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCB6F_BIT_5_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCB70_BIT_6_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCB71_BIT_6_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCB72_BIT_6_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCB73_BIT_6_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCB74_BIT_6_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCB75_BIT_6_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCB76_BIT_6_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCB77_BIT_6_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCB78_BIT_7_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCB79_BIT_7_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCB7A_BIT_7_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCB7B_BIT_7_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCB7C_BIT_7_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCB7D_BIT_7_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCB7E_BIT_7_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCB7F_BIT_7_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCB80_RES_0_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCB81_RES_0_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCB82_RES_0_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCB83_RES_0_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCB84_RES_0_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCB85_RES_0_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCB86_RES_0_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCB87_RES_0_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCB88_RES_1_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCB89_RES_1_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCB8A_RES_1_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCB8B_RES_1_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCB8C_RES_1_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCB8D_RES_1_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCB8E_RES_1_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCB8F_RES_1_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCB90_RES_2_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCB91_RES_2_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCB92_RES_2_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCB93_RES_2_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCB94_RES_2_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCB95_RES_2_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCB96_RES_2_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCB97_RES_2_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCB98_RES_3_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCB99_RES_3_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCB9A_RES_3_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCB9B_RES_3_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCB9C_RES_3_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCB9D_RES_3_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCB9E_RES_3_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCB9F_RES_3_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCBA0_RES_4_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCBA1_RES_4_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCBA2_RES_4_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCBA3_RES_4_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCBA4_RES_4_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCBA5_RES_4_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCBA6_RES_4_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCBA7_RES_4_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCBA8_RES_5_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCBA9_RES_5_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCBAA_RES_5_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCBAB_RES_5_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCBAC_RES_5_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCBAD_RES_5_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCBAE_RES_5_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCBAF_RES_5_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCBB0_RES_6_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCBB1_RES_6_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCBB2_RES_6_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCBB3_RES_6_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCBB4_RES_6_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCBB5_RES_6_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCBB6_RES_6_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCBB7_RES_6_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCBB8_RES_7_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCBB9_RES_7_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCBBA_RES_7_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCBBB_RES_7_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCBBC_RES_7_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCBBD_RES_7_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCBBE_RES_7_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCBBF_RES_7_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCBC0_SET_0_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCBC1_SET_0_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCBC2_SET_0_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCBC3_SET_0_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCBC4_SET_0_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCBC5_SET_0_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCBC6_SET_0_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCBC7_SET_0_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCBC8_SET_1_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCBC9_SET_1_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCBCA_SET_1_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCBCB_SET_1_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCBCC_SET_1_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCBCD_SET_1_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCBCE_SET_1_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCBCF_SET_1_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCBD0_SET_2_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCBD1_SET_2_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCBD2_SET_2_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCBD3_SET_2_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCBD4_SET_2_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCBD5_SET_2_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCBD6_SET_2_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCBD7_SET_2_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCBD8_SET_3_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCBD9_SET_3_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCBDA_SET_3_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCBDB_SET_3_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCBDC_SET_3_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCBDD_SET_3_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCBDE_SET_3_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCBDF_SET_3_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCBE0_SET_4_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCBE1_SET_4_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCBE2_SET_4_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCBE3_SET_4_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCBE4_SET_4_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCBE5_SET_4_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCBE6_SET_4_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCBE7_SET_4_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCBE8_SET_5_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCBE9_SET_5_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCBEA_SET_5_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCBEB_SET_5_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCBEC_SET_5_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCBED_SET_5_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCBEE_SET_5_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCBEF_SET_5_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCBF0_SET_6_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCBF1_SET_6_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCBF2_SET_6_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCBF3_SET_6_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCBF4_SET_6_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCBF5_SET_6_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCBF6_SET_6_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCBF7_SET_6_A(Cpu* cpu); 
		static uint8_t Instr_16_0xCBF8_SET_7_B(Cpu* cpu); 
		static uint8_t Instr_16_0xCBF9_SET_7_C(Cpu* cpu); 
		static uint8_t Instr_16_0xCBFA_SET_7_D(Cpu* cpu); 
		static uint8_t Instr_16_0xCBFB_SET_7_E(Cpu* cpu); 
		static uint8_t Instr_16_0xCBFC_SET_7_H(Cpu* cpu); 
		static uint8_t Instr_16_0xCBFD_SET_7_L(Cpu* cpu); 
		static uint8_t Instr_16_0xCBFE_SET_7_HL(Cpu* cpu);
		static uint8_t Instr_16_0xCBFF_SET_7_A(Cpu* cpu); 


		// helpers
		static void INC(Cpu* cpu, uint8_t& reg);
		static void INC_HL(Cpu* cpu);
		static void DEC(Cpu* cpu, uint8_t& reg);
		static void DEC_HL(Cpu* cpu);
		static void ADD(Cpu* cpu, uint8_t& reg);
		static void ADD_HL(Cpu* cpu);
		static void ADC(Cpu* cpu, uint8_t& reg);
		static void ADC_HL(Cpu* cpu);
		static void SUB(Cpu* cpu, uint8_t& reg);
		static void SUB_HL(Cpu* cpu);
		static void SBC(Cpu* cpu, uint8_t& reg);
		static void SBC_HL(Cpu* cpu);
		static void AND(Cpu* cpu, uint8_t& reg);
		static void AND_HL(Cpu* cpu);
		static void XOR(Cpu* cpu, uint8_t& reg);
		static void XOR_HL(Cpu* cpu);
		static void OR(Cpu* cpu, uint8_t& reg);
		static void OR_HL(Cpu* cpu);
		static void CP(Cpu* cpu, uint8_t& reg);
		static void CP_HL(Cpu* cpu);
		static void ADD_REG16(Cpu* cpu, uint16_t& reg);

		// prefix helpers
		static void RLC(Cpu* cpu, uint8_t& reg);
		static void RLC_HL(Cpu* cpu);
		static void RRC(Cpu* cpu, uint8_t& reg);
		static void RRC_HL(Cpu* cpu);
		static void RL(Cpu* cpu, uint8_t& reg);
		static void RL_HL(Cpu* cpu);
		static void RR(Cpu* cpu, uint8_t& reg);
		static void RR_HL(Cpu* cpu);
		static void SLA(Cpu* cpu, uint8_t& reg);
		static void SLA_HL(Cpu* cpu);
		static void SRA(Cpu* cpu, uint8_t& reg);
		static void SRA_HL(Cpu* cpu);
		static void SWAP(Cpu* cpu, uint8_t& reg);
		static void SWAP_HL(Cpu* cpu);
		static void SRL(Cpu* cpu, uint8_t& reg);
		static void SRL_HL(Cpu* cpu);
		static void BIT(Cpu* cpu, uint8_t& reg, uint8_t bit);
		static void BIT_HL(Cpu* cpu, uint8_t bit);
		static void RES(uint8_t& reg, uint8_t bit);
		static void RES_HL(Cpu* cpu, uint8_t bit);
		static void SET(uint8_t& reg, uint8_t bit);
		static void SET_HL(Cpu* cpu, uint8_t bit);
	};
}