#pragma once

constexpr double CLOCK_SPEED_MHZ = 4.194304; // 4.194304 MHz
constexpr double INSTRUCTION_TIME_SEC = 1.0 / CLOCK_SPEED_MHZ;

typedef enum
{
	/* Input */
	HW_P1JOYP_JOYPAD = 0xFF00,
	

	/* Misc */
	HW_SB_SERIAL_TRANSFER_DATA = 0xFF01,
	HW_SC_SERIAL_TRANSFER_CONTROL = 0xFF02,
	
	HW_DIV_DIVIDER_REGISTER = 0xFF04,
	HW_TIMA_TIMER_COUNTER = 0xFF05,
	HW_TMA_TIMER_MODULO = 0xFF06,
	HW_TAC_TIMER_CONTROL = 0xFF07,

	HW_IF_INTERRUPT_FLAG = 0xFF0F,


	/* Audio */
	HW_NR10_SOUND_CHANNEL_1_SWEEP = 0xFF10,
	HW_NR11_SOUND_CHANNEL_1_LEN_TIMER = 0xFF11,
	HW_NR12_SOUND_CHANNEL_1_VOL_ENVELOPE = 0xFF12,
	HW_NR13_SOUND_CHANNEL_1_PERIOD_LOW = 0xFF13,
	HW_NR14_SOUND_CHANNEL_1_PERIOD_HIGH = 0xFF14,
	HW_NR21_SOUND_CHANNEL_2_LEN_TIMER = 0xFF16,
	HW_NR22_SOUND_CHANNEL_2_VOL_ENVELOPE = 0xFF17,
	HW_NR23_SOUND_CHANNEL_2_PERIOD_LOW = 0xFF18,
	HW_NR24_SOUND_CHANNEL_2_PERIOD_HIGH = 0xFF19,
	HW_NR30_SOUND_CHANNEL_3_DAC_ENABLE = 0xFF1A,
	HW_NR31_SOUND_CHANNEL_3_LEN_TIMER = 0xFF1B,
	HW_NR32_SOUND_CHANNEL_3_OUTPUT_LEVEL = 0xFF1C,
	HW_NR33_SOUND_CHANNEL_3_PERIOD_LOW = 0xFF1D,
	HW_NR34_SOUND_CHANNEL_3_PERIOD_HIGH = 0xFF1E,
	HW_NR41_SOUND_CHANNEL_4_LEN_TIMER = 0xFF20,
	HW_NR42_SOUND_CHANNEL_4_VOL_ENVELOPE = 0xFF21,
	HW_NR43_SOUND_CHANNEL_4_FREQ_RANDOM = 0xFF22,
	HW_NR44_SOUND_CHANNEL_4_CONTROL = 0xFF23,
	HW_NR50_MASTER_VOLUME = 0xFF24,
	HW_NR51_SOUND_PANNING = 0xFF25,
	HW_NR52_SOUND_TOGGLE = 0xFF26,
	HW_WAVRAM_WAVEFORM_STORAGE = 0xFF30, // $FF30-FF3F

	/* Video */
	HW_LCDC_LCD_CONTROL = 0xFF40,
	HW_STAT_LCD_STATUS = 0xFF41,

	HW_SCY_VIEWPORT_Y_POS = 0xFF42,
	HW_SCX_VIEWPORT_X_POS = 0xFF43,

	HW_LY_LCD_Y_COORD = 0xFF44,
	HW_LYC_LY_COMPARE = 0xFF45,

	HW_DMA_OAM_DMA_SOURCE_ADDRESS = 0xFF46,
	HW_BGP_BG_PALETTE_DATA = 0xFF47,
	HW_OBP0_OBJ_PALETTE_0_DATA = 0xFF48,
	HW_OBP1_OBJ_PALETTE_1_DATA = 0xFF49,

	HW_WY_WINDOW_Y_POS = 0xFF4A,
	HW_WX_WINDOW_X_POS = 0xFF4B,

	/* Interrupt Toggle */
	HW_INTERRUPT_ENABLE = 0xFFFF
	
} HardwareAddresses;

typedef enum
{
	MODE_0_HBLANK =  0,  // Horizontal Blank
	MODE_1_VBLANK =  1,  // Vertical Blank
	MODE_2_OAMSCAN = 2, // OAM Scan
	MODE_3_DRAWING = 3  // Drawing Pixels
} LCD_Mode;

typedef enum
{
	LCDC_BG_WINDOW_ENABLE_PRIORITY = 0x01,
	LCDC_OBJ_ENABLE = 0x02,
	LCDC_OBJ_SIZE = 0x04,
	LCDC_BG_TILE_MAP = 0x08,
	LCDC_BG_AND_WINDOW_TILES = 0x10,
	LCDC_WINDOW_ENABLE = 0x20,
	LCDC_WINDOW_TILE_MAP = 0x40,
	LCDC_LCD_PPU_ENABLE = 0x80
} LCDC_Flags;

typedef enum
{
	STAT_PPU_MODE = 0x01, // this is two bits !!
	STAT_LYC_EQUAL_LY = 0x04,
	STAT_MODE_0_INT_SELECT = 0x08,
	STAT_MODE_1_INT_SELECT = 0x10,
	STAT_MODE_2_INT_SELECT = 0x20,
	STATE_LYC_INT_SELECT = 0x40
} STAT_FLags;